### ISSUE TITLE
fatal error: cuda/include/cuda.h: No such file or directory

### ISSUE THREAD

**Issue by nguyeho7** [zengarden/light_head_rcnn#9]
Hello, 
I'm running this in a docker container with cuda 9.0 and tensorflow 1.5.0 installed from pip3.
When I run make.sh it get's stuck while compiling psroi_pooling_op_gpu.cu.cc. 
The exact error message is as follows:

```
In file included from psalign_pooling_op_gpu.cu.cc:7:0:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/util/cuda_kernel_helper.h:24:31: fatal error: cuda/include/cuda.h: No such file or directory
```

Do I have to compile tensorflow from source?

**Comment by zengarden** [comment]
@nguyeho7   Try follows:
 
```
 24 #include "cuda.h"
```

**Comment by nguyeho7** [comment]
Thank you, editing ```cuda/include/cuda.h``` to ```"cuda.h"``` in two .h files worked!

**Comment by Mampfi93** [comment]
Worked for me as well.
Thanks for your support!
Modified cuda_launch_config.h and cuda_device_functions.h

**Comment by liuhengli** [comment]
After modify #include "cuda.h"  
Appear fatal error: cuda/cuda_config.h: No such file or directory

**Comment by liuhengli** [comment]
@nguyeho7 @Mampfi93

**Comment by Mampfi93** [comment]
@liuhengli as I didn't get this error I can just refere to the FAQ. There's a solution given for your problem.

> 
    fatal error: cuda/cuda_config.h: No such file or directory

First, find where is cuda_config.h.

e.g.

find /usr/local/lib/ | grep cuda_config.h

then export your cpath, like:

export CPATH=$CPATH:/usr/local/lib/python3.5/dist-packages/external/local_config_cuda/cuda/

**Comment by liuhengli** [comment]
@Mampfi93 thanks, you are right. it worked.

**Comment by vedrusss** [comment]
Just to resume all solutions above.
I had the issue + one more which looked like
1 error detected in the compilation of "/tmp/tmpxft_00002821_00000000-7_roi_pooling_op_gpu.cu.cpp1.ii".
g++: error: roi_pooling_op.cu.o: No such file or directory

The solution that helped me:
1. Re-install tensorflow-gpu as root. I had it installed into /home/myuser previously. If you have it the same just do
  pip3 uninstall tensorflow-gpu
  sudo pip3 install tensorflow-gpu==1.5.0
2.  Use solution proposed by @zengarden above. To get known within which two files you must correct those '#include' you may run first ./make.sh and take paths from obtained errors.
3. Instead of correcting path to cuda_config.h (the 3rd error) use solution provided by @smoosbau above (but it works only if tensorflow-gpu installed under root - see #1).

After used that steps I was finally able to build the project.

**Comment by karansomaiah** [comment]
I also faced a similar problem regarding cuda_fp16.h file.
I changed 'cuda/include/cuda_fp16.h' to 'cuda_fp16.h' in the cuda_kernel_helper.h file and resolved the issue.
